package weaver.cpt.util;

import org.json.JSONArray;
import org.json.JSONObject;
import weaver.conn.RecordSet;
import weaver.cpt.util.CptFieldManager;
import weaver.general.BaseBean;
import weaver.general.TimeUtil;
import weaver.hrm.User;
import weaver.systeminfo.SystemEnv;

public class CptDetailColumnUtilNew extends BaseBean {
    private RecordSet rs = new RecordSet();
    private CptFieldManager cptFieldManager = new CptFieldManager();

    public CptDetailColumnUtilNew() {
    }

    public JSONArray getDetailColumnConf(String var1, User var2) {
        JSONArray var3 = new JSONArray();
        new JSONObject();

        try {
            JSONObject var4;
            if("CptStockInDetail".equalsIgnoreCase(var1)) {
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1509, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp?type=23&isdata=1\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/cpt/capital/CapitalBrowser.jsp?sqlwhere=where isdata=1\' name=\'capitalid\' isMustInput=\'2\' hasInput=\'true\'  isSingle=\'true\' _callback=\'loadinfo\' ></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(904, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'capitalspec\' id=\'capitalspec\' /><span class=\'mustinput\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1330, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'price\' maxLength=\'7\' id=\'price\' onkeyup=\"value=value.replace(/[^\\d\\.]/g,\'\')\"  /><span class=\'mustinput\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1331, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'capitalnum\' maxLength=\'7\' id=\'capitalnum\' onkeyup=\"value=value.replace(/[^\\d\\.]/g,\'\')\" /><span class=\'mustinput\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(900, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'invoice\' id=\'invoice\' />");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1387, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'location\' id=\'location\' />");
                var3.put(var4);
            } else if("CptUse".equalsIgnoreCase(var1)) {
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1412, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'hidden\' name=\'StockInDate\' value=\'" + TimeUtil.getCurrentDateString() + "\'   class=\'wuiDate\' style=\'width:90px!important;\'  _span=\'StockInDate_span\' _button=\'StockInDate_btn\' _callback=\'\' >");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15312, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/interface/CommonBrowser.jsp?type=browser.FL_CAPITAL_USE\' name=\'capitalid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\'  _callback=\'loadinfo\'  ></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(368, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/hrm/resource/ResourceBrowser.jsp\' name=\'hrmid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(904, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'capitalspec_span\' name=\'capitalspec_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "5%");
                var4.put("colname", SystemEnv.getHtmlLabelName(714, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'code_span\' name=\'code_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1446, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'capitalcount_span\' name=\'capitalcount_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15313, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'capitalnum\' id=\'capitalnum\' size=\'5\' maxlength=\'5\' onkeyup=\"value=value.replace(/[^\\d\\.]/g,\'\')\" /><span class=\'mustinput\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1387, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'location\' id=\'location\' size=\'10\' maxlength=\'10\' />");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(454, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'remark\' id=\'remark\' />");
                var3.put(var4);
            } else if("CptMove".equalsIgnoreCase(var1)) {
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15310, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/hrm/resource/ResourceBrowser.jsp\' name=\'hrmid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\' _callback=\'\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15311, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp?type=4\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/hrm/company/DepartmentBrowser.jsp\' name=\'CptDept_to\' isMustInput=\'2\' hasInput=\'true\' isSingle=\'true\' _callback=\'\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15309, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp?type=23&cptstateid=2\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/cpt/capital/CapitalBrowser.jsp?sqlwhere=where isdata=2&cptstateid=2\' name=\'capitalid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\' _callback=\'loadinfo\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(524, var2.getLanguage()) + SystemEnv.getHtmlLabelName(15393, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'curdept_span\' name=\'curdept_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(524, var2.getLanguage()) + SystemEnv.getHtmlLabelName(1508, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'curresource_span\' name=\'curresource_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(904, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'capitalspec_span\' name=\'capitalspec_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1387, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'location\' id=\'location\' size=\'10\' maxlength=\'10\' />");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "30%");
                var4.put("colname", SystemEnv.getHtmlLabelName(454, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'remark\' id=\'remark\' />");
                var3.put(var4);
            } else if("CptLend".equalsIgnoreCase(var1)) {
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelNames("1379,368", var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/hrm/resource/ResourceBrowser.jsp\' name=\'hrmid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\' _callback=\'\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1404, var2.getLanguage()));
                var4.put("itemhtml", "<input name=\'StockInDate\' type=\'hidden\' value=\'" + TimeUtil.getCurrentDateString() + "\'   class=\'wuiDate\' style=\'width:90px!important;\'  _span=\'StockInDate_span\' _button=\'StockInDate_btn\' _callback=\'\' >");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1379, var2.getLanguage()) + SystemEnv.getHtmlLabelName(535, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp?type=23&cptstateid=1&cptsptcount=1\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/cpt/capital/CapitalBrowser.jsp?sqlwhere=where isdata=2&cptstateid=1&cptsptcount=1\' name=\'capitalid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\' _callback=\'loadinfo\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15393, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'curdept_span\' name=\'curdept_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(524, var2.getLanguage()) + SystemEnv.getHtmlLabelName(1508, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'curresource_span\' name=\'curresource_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(904, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'capitalspec_span\' name=\'capitalspec_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1387, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'location\' id=\'location\' size=\'10\' maxlength=\'10\' />");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "30%");
                var4.put("colname", SystemEnv.getHtmlLabelName(454, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'remark\' id=\'remark\' />");
                var3.put(var4);
            } else if("CptLoss".equalsIgnoreCase(var1)) {
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(17482, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/hrm/resource/ResourceBrowser.jsp\' name=\'operator\' hasInput=\'true\' isMustInput=\'1\' isSingle=\'true\' _callback=\'\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1406, var2.getLanguage()));
                var4.put("itemhtml", "<input name=\'StockInDate\' type=\'hidden\' value=\'" + TimeUtil.getCurrentDateString() + "\'   class=\'wuiDate\' style=\'width:90px!important;\'  _span=\'StockInDate_span\' _button=\'StockInDate_btn\' _callback=\'\' >");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1385, var2.getLanguage()) + SystemEnv.getHtmlLabelName(535, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp?type=23\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/cpt/capital/CapitalBrowser.jsp\' name=\'capitalid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\' _callback=\'loadinfo\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15393, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'curdept_span\' name=\'curdept_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(904, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'capitalspec_span\' name=\'capitalspec_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1451, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'capitalcount_span\' name=\'capitalcount_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1385, var2.getLanguage()) + SystemEnv.getHtmlLabelName(1331, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'capitalnum\' id=\'capitalnum\' size=\'5\' maxlength=\'5\' onkeyup=\"value=value.replace(/[^\\d\\.]/g,\'\')\" /><span class=\'mustinput\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1393, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'cost\' id=\'cost\' size=\'10\' maxlength=\'10\' onkeyup=\"value=value.replace(/[^\\d\\.]/g,\'\')\" />");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(454, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'remark\' id=\'remark\' />");
                var3.put(var4);
            } else if("CptDiscard".equalsIgnoreCase(var1)) {
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(17482, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/hrm/resource/ResourceBrowser.jsp\' name=\'operator\' hasInput=\'true\' isMustInput=\'1\' isSingle=\'true\' _callback=\'\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1392, var2.getLanguage()));
                var4.put("itemhtml", "<input name=\'StockInDate\' type=\'hidden\' value=\'" + TimeUtil.getCurrentDateString() + "\'   class=\'wuiDate\' style=\'width:90px!important;\'  _span=\'StockInDate_span\' _button=\'StockInDate_btn\' _callback=\'\' >");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(21545, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp?type=23&cptstateid=1,2,3,4\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/cpt/capital/CapitalBrowser.jsp?sqlwhere=where isdata=2&cptstateid=1,2,3,4\' name=\'capitalid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\' _callback=\'loadinfo\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15393, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'curdept_span\' name=\'curdept_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(904, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'capitalspec_span\' name=\'capitalspec_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1451, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'capitalcount_span\' name=\'capitalcount_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1386, var2.getLanguage()) + SystemEnv.getHtmlLabelName(1331, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'capitalnum\' id=\'capitalnum\' size=\'5\' maxlength=\'5\' onkeyup=\"value=value.replace(/[^\\d\\.]/g,\'\')\" /><span class=\'mustinput\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1393, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'cost\' id=\'cost\' size=\'10\' maxlength=\'10\' onkeyup=\"value=value.replace(/[^\\d\\.]/g,\'\')\" />");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(454, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'remark\' id=\'remark\' />");
                var3.put(var4);
            } else if("CptMend".equalsIgnoreCase(var1)) {
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1047, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\'  completeurl=\'/data.jsp\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/hrm/resource/ResourceBrowser.jsp\' name=\'operator\' hasInput=\'true\' isMustInput=\'1\' isSingle=\'true\' _callback=\'\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1409, var2.getLanguage()));
                var4.put("itemhtml", "<input name=\'menddate\' type=\'hidden\' value=\'" + TimeUtil.getCurrentDateString() + "\'   class=\'wuiDate\' style=\'width:90px!important;\'  _span=\'menddate_span\' _button=\'menddate_btn\' _callback=\'\' >");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(22457, var2.getLanguage()));
                var4.put("itemhtml", "<input name=\'mendperioddate\' type=\'hidden\' value=\'\'   class=\'wuiDate\' style=\'width:90px!important;\'  _span=\'mendperioddate_span\' _button=\'mendperioddate_btn\' _callback=\'\' >");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1399, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp?type=7\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/crm/data/CustomerBrowser.jsp?sqlwhere=where t1.type=2\' name=\'maintaincompany\' hasInput=\'true\' isMustInput=\'1\' isSingle=\'true\' _callback=\'\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName('аи', var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp?type=23&cptstateid=1,2,3&cptsptcount=1\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/cpt/capital/CapitalBrowser.jsp?sqlwhere=where isdata=2&cptstateid=1,2,3&cptsptcount=1\' name=\'capitalid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\' _callback=\'loadinfo\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15393, var2.getLanguage()));
                var4.put("itemhtml", "<span  id=\'curdept_span\' name=\'curdept_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(904, var2.getLanguage()));
                var4.put("itemhtml", "<span  id=\'capitalspec_span\' name=\'capitalspec_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(602, var2.getLanguage()));
                var4.put("itemhtml", "<span  id=\'status_span\' name=\'status_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "6%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1393, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' style=\'width:50px!important;\' name=\'cost\' id=\'cost\' size=\'10\' maxlength=\'10\' onkeyup=\"value=value.replace(/[^\\d\\.]/g,\'\')\" />");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "6%");
                var4.put("colname", SystemEnv.getHtmlLabelName(454, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' style=\'width:50px!importan;\' name=\'remark\' id=\'remark\' />");
                var3.put(var4);
            } else if("CptBack".equalsIgnoreCase(var1)) {
                var4 = new JSONObject();
                var4.put("width", "6%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1413, var2.getLanguage()));
                var4.put("itemhtml", "<input name=\'StockInDate\' type=\'hidden\' value=\'" + TimeUtil.getCurrentDateString() + "\'   class=\'wuiDate\' style=\'width:90px!important;\'  _span=\'menddate_span\' _button=\'menddate_btn\' _callback=\'\' >");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "15%");
                var4.put("colname", SystemEnv.getHtmlLabelName(1384, var2.getLanguage()) + SystemEnv.getHtmlLabelName(535, var2.getLanguage()));
                var4.put("itemhtml", "<span class=\'browser\' completeurl=\'/data.jsp?type=23&cptstateid=2,3,4\' browserurl=\'/systeminfo/BrowserMain.jsp?url=/cpt/capital/CapitalBrowser.jsp?sqlwhere=where isdata=2&cptstateid=2,3,4\' name=\'capitalid\' hasInput=\'true\' isMustInput=\'2\' isSingle=\'true\' _callback=\'loadinfo\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15393, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'curdept_span\' name=\'curdept_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(904, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'capitalspec_span\' name=\'capitalspec_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(602, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'status_span\' name=\'status_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "8%");
                var4.put("colname", SystemEnv.getHtmlLabelName(524, var2.getLanguage()) + SystemEnv.getHtmlLabelName(1508, var2.getLanguage()));
                var4.put("itemhtml", "<span id=\'curresource_span\' name=\'curresource_span\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(454, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'remark\' id=\'remark\' />");
                var3.put(var4);
            } else if("CptDefineField".equalsIgnoreCase(var1)) {
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelNames("15024,685", var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'itemDspName\' id=\'itemDspName\' size=\'15\' maxlength=\'30\' onblur=\"checkKey(this);checkinput_char_num(this.name);\" /><span class=\'mustinput\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(15456, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' name=\'itemFieldName\' id=\'itemFieldName\' onblur=\"checkKey(this);\" /><span class=\'mustinput\'></span>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "50%");
                var4.put("colname", SystemEnv.getHtmlLabelName(686, var2.getLanguage()));
                var4.put("itemhtml", "" + this.cptFieldManager.getItemFieldTypeSelectForAddMainRow2(var2));
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(18095, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'checkbox\'  name=\'isopen\' id=\'isopen\' value=\'1\' checked>");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(18019, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'checkbox\'  onchange=\'\' name=\'ismand\' value=\'1\' >");
                var3.put(var4);
                var4 = new JSONObject();
                var4.put("width", "10%");
                var4.put("colname", SystemEnv.getHtmlLabelName(88, var2.getLanguage()));
                var4.put("itemhtml", "<input type=\'text\' size=10 maxlength=7 name=\'itemDspOrder\' value=\'\'  onKeyPress=\'ItemNum_KeyPress(this.name)\' onchange=\'checknumber(this.name);checkDigit(this.name,15,2)\' style=\'text-align:right;\' />");
                var3.put(var4);
            }
        } catch (Exception var6) {
            var6.printStackTrace();
            this.writeLog(var6.getMessage());
        }

        return var3;
    }
}
